# All Spotify track IDs — 300+ songs across 3 languages and 10 moods
LANG_SONGS = {
    "hi": {
        "happy": [
            {"title": "Badtameez Dil", "sp": "4eu27jAU2bbnyHUC3G75U8"},
            {"title": "Gallan Goodiyaan", "sp": "7hNYvX0qAKrxtVr1jGDmvR"},
            {"title": "London Thumakda", "sp": "2qJAzSE6uC94oH2NRoPrGl"},
            {"title": "Balam Pichkari", "sp": "18e3XXYCv4Tx8uUl1mP3CN"},
            {"title": "Kar Gayi Chull", "sp": "3BhjbaGeI7E0CiIjctfdD3"},
            {"title": 'Bekhayali (From "Kabir Singh")', "sp": "1feANd8EfcDP5UqSvbheM3"},
            {"title": 'Ghungroo (From "War")', "sp": "0WdbnNKO0Jt4BZACSDQh44"},
            {"title": "Jugnu", "sp": "2NTVtNcpC0i1R7LVGaCZCF"},
            {"title": "Paani Paani", "sp": "47Rqh5ZSamtIOFi7G6VgFJ"},
            {"title": 'Dheeme Dheeme (From "Pati Patni Aur Woh")', "sp": "7ofWUKeNCUw1P64ArIwG9b"},
            {"title": "Kala Chashma", "sp": "6mdLX10dvBb7rGYbMXpKzz"},
            {"title": 'Senorita (From "Zindagi Na Milegi Dobara")', "sp": "6b8zsc3BxT59Yg62wjt7qA"},
            {"title": 'Dilbar (From "Satyameva Jayate")', "sp": "6T7J8hJCnnxC2vvTznHtSG"},
            {"title": "Nachde Ne Saare", "sp": "7HuLB7m448hiKT7Af60Ew3"},
            {"title": "Tamma Tamma Again", "sp": "5sqPE9h98DkO5ms20NUiUg"},
            {
                "title": 'Gal Ban Gayi (From "Gal Ban Gayi") (feat. Sukhbir, Neha Kakkar, Yo Yo Honey Singh)',
                "sp": "5zsz7azbdnyRixDqThVmLq",
            },
            {"title": "Morni Banke", "sp": "5XxzNB2CnNrySvyVLwyobq"},
            {"title": "Gal Ban Gayee", "sp": "0IKzZkOoBqwbSWHXBv1eBv"},
            {"title": "Hauli Hauli", "sp": "4oU3ELywkFbHbHpqqBZYig"},
            {"title": 'What Jhumka ? (From "Rocky Aur Rani Kii Prem Kahaani")', "sp": "4QyX8CBSjcoq4iMZuvifyF"},
            {"title": "Jhoome Jo Pathaan", "sp": "6FAYpZ4jve8vpvTwUvjK6H"},
            {"title": "Tumse Hi Tumse", "sp": "6qNyL8lZuqFmy9ginJRQOZ"},
            {"title": "Slow Motion Angreza", "sp": "0JX7Es2j556FwtR6YqMKzP"},
            {"title": "Lamberghini", "sp": "45P9g6kUb7itdonjjGjDdS"},
            {"title": "Matargashti", "sp": "5GeBgck1MU2tlIkMpsn8uT"},
            {"title": "Kabhi Kabhi Aditi", "sp": "3APdIdF8H0jsxSuGOqXedS"},
            {"title": 'Aaj Ki Raat (From "Stree 2")', "sp": "5AnWrUzsrFgBvhn6dUElnr"},
        ],
        "sad": [
            {"title": 'Tujhe Kitna Chahne Lage (From "Kabir Singh")', "sp": "2Fv2injs4qAm8mJBGaxVKU"},
            {"title": 'Channa Mereya (From "Ae Dil Hai Mushkil")', "sp": "1plFCZ6QFAjSRutT02GTCn"},
            {"title": 'Agar Tum Saath Ho (From "Tamasha")', "sp": "2FCXQHugkoHE1K3tiDu8pu"},
            {"title": "Kabira", "sp": "4bD9z9qa4qg9BhryvYWB7c"},
            {"title": "Ae Dil Hai Mushkil Title Track", "sp": "1UWacd8x8tPPwmrPB1MoBI"},
            {"title": "Hamari Adhuri Kahani (Title Track)", "sp": "3HiobOOpSpMsi95WBKPBYk"},
            {"title": "Hasi - Female Version", "sp": "1cmZbGkCEVVAck2MsWpPYQ"},
            {"title": "Main Rahoon Ya Na Rahoon", "sp": "6f3ANRNQ8nCiPZ6VqXqq93"},
            {"title": "Channa Mereya", "sp": "0H2iJVgorRR0ZFgRqGUjUM"},
            {"title": "Teri Mitti", "sp": "6mkgbTsWDSgKkM6zF6Az71"},
        ],
        "romantic": [
            {"title": 'Tum Hi Ho (From "Aashiqui 2")', "sp": "3oKuEvvclPj25AifUVoKxS"},
            {"title": 'Raataan Lambiyan (From "Shershaah")', "sp": "2rOnSn2piaqLAlYjtfUBlY"},
            {"title": "Pehla Nasha", "sp": "6cCSo8zu3bRck519ZqRGfk"},
            {"title": 'Hawayein (From "Jab Harry Met Sejal")', "sp": "6871FKHumiy1Wfr6vF7Xxt"},
            {"title": 'Kesariya (From "Brahmastra")', "sp": "6VBhH7CyP56BXjp8VsDFPZ"},
            {"title": "Ranjha - Sid X Kiara Wedding Version", "sp": "1nvvaiJbrhCkM3Az74N1pM"},
            {"title": "Bairiya", "sp": "5oDqm3nmB6euAtKnDH8cQD"},
            {"title": "Chaand Baaliyan", "sp": "0snQrp1VaY5Pj1YIHRJpRJ"},
            {"title": 'Doobey (From "Gehraiyaan")', "sp": "7MBqVOzb8C3f0FXr2LBLiq"},
            {"title": 'Senorita (From "Zindagi Na Milegi Dobara")', "sp": "6b8zsc3BxT59Yg62wjt7qA"},
        ],
        "energetic": [
            {"title": 'Malhari - From "Bajirao Mastani"', "sp": "3ScscBqGhzWaeUlQbescWb"},
            {"title": "Dhoom Machale", "sp": "2cYVtBHkrkk7F2qU2Y7Fn0"},
            {"title": "Khalibali", "sp": "3JT0mVof65rIHpRZITwRx1"},
            {"title": "Shararat", "sp": "0R7grQWU1dRxiOQGIqZm0Z"},
            {"title": 'Aaj Ki Raat (From "Stree 2")', "sp": "5AnWrUzsrFgBvhn6dUElnr"},
            {"title": "Akhiyaan Gulaab", "sp": "0qPoQiQIhgyMaP7X78hxri"},
            {"title": "Halka Halka", "sp": "3DbNXniRprbs23Vlmy4roM"},
            {"title": "Mere Mehboob", "sp": "5ZjWYv5kOH1ywFmv5JjPNd"},
            {"title": "Jhoome Jo Pathaan", "sp": "6FAYpZ4jve8vpvTwUvjK6H"},
            {"title": 'Dilbar (From "Satyameva Jayate")', "sp": "6T7J8hJCnnxC2vvTznHtSG"},
        ],
        "stressed": [
            {"title": "Kun Faya Kun", "sp": "7F8RNvTQlvbeBLeenycvN6"},
            {"title": "Ilahi", "sp": "5cgKosPPj5Cs9a2JQufUc1"},
            {"title": 'Mann Bharryaa 2.0 (From "Shershaah")', "sp": "3jf5303mzzJ96O8xFTcEn4"},
            {"title": "Saibo", "sp": "6udC4b4jOSnHb9ItnXgKLR"},
            {"title": "Khuda Jaane", "sp": "0gPgdRfB4jdGrlyXS0Vx78"},
            {"title": "Raabta", "sp": "6FjbAnaPRPwiP3sciEYctO"},
            {"title": 'Pardesiya - From "Param Sundari"', "sp": "0q84FggW57NXGtLHoetS0Y"},
            {"title": 'Main Rang Sharbaton Ka (From "Phata Poster Nikhla Hero")', "sp": "7hNb5juMQyy93U63jW4Mwj"},
        ],
        "angry": [
            {"title": "Chak De India", "sp": "6D3vmtskO4RbZP3bBIDY3X"},
            {"title": "Dangal", "sp": "5Ry67OqwCxKbswCxcPHcg9"},
            {"title": 'Kar Har Maidaan Fateh (From "Sanju")', "sp": "3FHl1QYu76zguwjqhqcglX"},
            {"title": "Aarambh", "sp": "1PZZtXR7nsNIyRcqd7UeiF"},
            {"title": "Ravan", "sp": "3hrW1jobQYQJTaLdcs4m6L"},
            {"title": "Krantiveer Chapter I", "sp": "5OjjGtAxdgV66zsZv9N8vE"},
            {"title": "Brothers Anthem", "sp": "3uZiNvBNQldjl4OJiKsuxe"},
        ],
        "chill": [
            {"title": 'Iktara (From "Wake Up Sid")', "sp": "0bmp0lE3ArELHqda9PBMVG"},
            {"title": "Tum Se Hi", "sp": "7eQl3Yqv35ioqUfveKHitE"},
            {"title": 'Pardesiya - From "Param Sundari"', "sp": "0q84FggW57NXGtLHoetS0Y"},
            {"title": "Saibo", "sp": "6udC4b4jOSnHb9ItnXgKLR"},
            {"title": 'Main Rang Sharbaton Ka (From "Phata Poster Nikhla Hero")', "sp": "7hNb5juMQyy93U63jW4Mwj"},
            {"title": "Khuda Jaane", "sp": "0gPgdRfB4jdGrlyXS0Vx78"},
            {"title": "Raabta", "sp": "6FjbAnaPRPwiP3sciEYctO"},
            {"title": "Lag Ja Gale Se Phir", "sp": "5Y5c5bJK0O7KJDDAYKkppH"},
            {"title": 'Tu Hi Disda - From "Bhooth Bangla"', "sp": "4mjAJxu1OQMd0Pf5lOLNQL"},
        ],
        "nostalgic": [
            {"title": "Chaiyya Chaiyya", "sp": "5H4rKylLnO8KrmdXTRhj5s"},
            {"title": "Tujh Mein Rab Dikhta Hai", "sp": "2LcXJP95e4HKydTZ2mYfrx"},
            {"title": "Rang De Basanti", "sp": "1SdFBc40uBU5Pqylo05VIC"},
            {"title": "Kabira", "sp": "4bD9z9qa4qg9BhryvYWB7c"},
            {"title": "Pehla Nasha", "sp": "6cCSo8zu3bRck519ZqRGfk"},
            {"title": "Lag Ja Gale Se Phir", "sp": "5Y5c5bJK0O7KJDDAYKkppH"},
        ],
        "confident": [
            {"title": "Apna Time Aayega", "sp": "5FLgOuLoVwwUUF7IL36Lux"},
            {"title": "Zinda", "sp": "7vZz8oJ5qAqB9MghufRK5k"},
            {"title": "Sultan - Title Track Salman Khan Version", "sp": "3LJhJG3EsmhCq9bNn047lu"},
            {"title": "Aarambh", "sp": "1PZZtXR7nsNIyRcqd7UeiF"},
            {"title": "Parwah Nahin", "sp": "59RXttbK7hgRfnMTMVg2xm"},
            {"title": "Dangal", "sp": "7EpZ8kdKyQM4GMJy2tj0We"},
            {"title": "Panga Title Track", "sp": "2x9ENEAOQ2oCuoetsDdEnf"},
            {"title": "Brothers Anthem", "sp": "3uZiNvBNQldjl4OJiKsuxe"},
            {"title": "Dangal", "sp": "5Ry67OqwCxKbswCxcPHcg9"},
        ],
        "bored": [
            {"title": "Nagada Sang Dhol", "sp": "7tuP0eTcNhPXYzdhNrwMBt"},
            {"title": "Tune Maari Entriyaan", "sp": "5kg1GacbhgQfLcbgOBRO9c"},
            {"title": "Badri Ki Dulhania (Title Track)", "sp": "2xbvLQBFW7E9232BwMBljb"},
            {"title": "Gallan Goodiyaan", "sp": "7hNYvX0qAKrxtVr1jGDmvR"},
            {"title": "Lamberghini", "sp": "45P9g6kUb7itdonjjGjDdS"},
            {"title": 'Dilbar (From "Satyameva Jayate")', "sp": "6T7J8hJCnnxC2vvTznHtSG"},
            {"title": "Tamma Tamma Again", "sp": "5sqPE9h98DkO5ms20NUiUg"},
            {
                "title": 'Gal Ban Gayi (From "Gal Ban Gayi") (feat. Sukhbir, Neha Kakkar, Yo Yo Honey Singh)',
                "sp": "5zsz7azbdnyRixDqThVmLq",
            },
            {"title": "Hauli Hauli", "sp": "4oU3ELywkFbHbHpqqBZYig"},
        ],
    },
    "te": {
        "happy": [
            {"title": "Buttabomma - Telugu", "sp": "0dnDTvdUco2UbaBjUtPxNS"},
            {"title": "Ramuloo Ramulaa - Duet", "sp": "4uXJADmybUHUgycBWFHeq6"},
            {"title": "Samajavaragamana", "sp": "3j9DrRebdWK1jkpOw9FZUy"},
            {"title": 'Srivalli (From "Pushpa The Rise Part - 01")', "sp": "7sVEoPc5ZUUQerRkgTypUZ"},
            {"title": 'Naatu Naatu (From "Rrr")', "sp": "4iKGu3xtvm90eBw0EIPWJP"},
            {"title": 'Ranjithame (From "Vaarasudu") [Telugu]', "sp": "0gZibDOwioMCck3d5nExjl"},
            {"title": "Jinthaak Chithaka", "sp": "7tVR9J6R4KFlU3CJUCEdxQ"},
            {"title": "Dandakadiyal", "sp": "7AQdK2O5TIOKZ5GMdgJNOz"},
            {"title": "Mass Raja", "sp": "4zpMp6HkV9mT7z8FCnovI2"},
            {"title": "Suguna Sundari", "sp": "1E0uPi2rjMgcZ3ayODv6DX"},
            {"title": "Saranga Dariya", "sp": "74IQCxI4nws964fic1Q4pv"},
            {"title": "Kurchi Madathapetti", "sp": "4X09IuSKCHSrwtZuGoJD0r"},
        ],
        "sad": [
            {"title": "Inkem Inkem Inkem Kaavaale", "sp": "3hglFJgXWPZUlHLfiDO35b"},
            {"title": "Nee Kannu Neeli Samudram - Telugu", "sp": "1C9SYGI40nNYh98gN87Fwr"},
            {"title": "Emai Poyave", "sp": "14M1StehpwsydSGGy8z9eq"},
            {"title": "Undiporaadhey Sad Version", "sp": "18r28YOE2nO8hU0bv0lmcv"},
            {"title": "Selavanuko", "sp": "6ciYv5q2QoZo1lBTdDfzRT"},
            {"title": "Adigaa", "sp": "4k9RLcTWZog34sIXt23Ibr"},
            {"title": "Telisiney Na Nuvvey", "sp": "6f7qFjos0WWqvtEnwFDS0a"},
            {"title": "Pranam Pothunna", "sp": "2yyOgnukcQCppigRdL0IX1"},
        ],
        "romantic": [
            {"title": "Inkem Inkem Inkem Kaavaale", "sp": "3hglFJgXWPZUlHLfiDO35b"},
            {"title": "Samajavaragamana", "sp": "3j9DrRebdWK1jkpOw9FZUy"},
            {"title": "Vachinde", "sp": "2MeFfFMbaRDokOKwCJoxR8"},
            {"title": 'Rubaroo (From "Dacoit (Telugu)")', "sp": "3M3bCnAOydcZJ0pCUi04Qc"},
            {"title": "Naalo Nenu", "sp": "33zE3PueaFRUBymwooP4yC"},
            {"title": "Jaabili Jaana", "sp": "2sNW5fKLTRKzUrT2NwRptj"},
            {"title": 'Sahana Sahana (From "The Rajasaab") [TELUGU]', "sp": "5xOEnyX9CddnBbUNLmbW7X"},
            {"title": "Oka Lailakosam", "sp": "0ijX4tdjjiiWXWIk5PxcEE"},
        ],
        "energetic": [
            {"title": 'Naatu Naatu (From "Rrr")', "sp": "4iKGu3xtvm90eBw0EIPWJP"},
            {"title": 'Oo Antava Oo Oo Antava (From "Pushpa - The Rise")(Telugu)', "sp": "3szxldqiYs7nkvtmooRod8"},
            {"title": "Mind Block", "sp": "4q4PNCWRo90nUTILn6Y048"},
            {"title": "Jigelu Rani", "sp": "0dw216k4UD9HVVNnXLMziC"},
            {"title": 'Dhaari Choodu (From "Krishnarjuna Yudham")', "sp": "3BBI3rftKYwZAuuIa1Z9fY"},
            {"title": "Ammadu Let's Do Kummudu", "sp": "2qPJtWoPESkEDsmDntnVpE"},
            {"title": "Nela Ticket", "sp": "11FVlM1qUjNPm2xEt3aaCA"},
            {"title": "Ranga Ranga Rangasthalaana", "sp": "2IlyfBbgvh7tU7t5kRntjA"},
            {"title": "Pakka Local", "sp": "5rPM9EITEGWpCJYIcedu6q"},
            {"title": "Vachaadayyo Saami", "sp": "4TcKIevH4QdFuJdSWZKLjU"},
            {"title": "Kurchi Madathapetti", "sp": "4X09IuSKCHSrwtZuGoJD0r"},
        ],
        "stressed": [
            {"title": "Vachinde", "sp": "2MeFfFMbaRDokOKwCJoxR8"},
            {"title": "Choosi Chudangane", "sp": "2PLxApcPeSnpfEpa6MPiuR"},
            {"title": "Neeli Meghamulalo", "sp": "0KI7IWhPBmzM4x059v5W6d"},
            {"title": "Modalainthile (Telugu Version)", "sp": "2FvDAZiQ9K53xFjFrsGx5e"},
            {"title": "Em Jaruguthondhi", "sp": "2bmUK5Th4OChl5q1H028qa"},
        ],
        "angry": [
            {"title": 'Komuram Bheemudo (From "Rrr")', "sp": "7G8LfMpY6TGN9dbZ9m0Jdd"},
            {"title": "Saahore Baahubali", "sp": "0bRCRY10cmf7RuXMvblAks"},
            {"title": 'Eyy Bidda Idhi Naa Adda (From "Pushpa - The Rise")(Telugu)', "sp": "7e6J0HgooHYVi4SwdOB2OM"},
            {"title": 'Dhaari Choodu (From "Krishnarjuna Yudham")', "sp": "3BBI3rftKYwZAuuIa1Z9fY"},
            {"title": "Nela Ticket", "sp": "11FVlM1qUjNPm2xEt3aaCA"},
        ],
        "chill": [
            {"title": "MAYA CHESESAVE", "sp": "0aJocuPLwipMx6YmqjCiuw"},
            {"title": "Ninnu Kori Tittle Song", "sp": "0pvuuiVNM9fx8r2ppPae2e"},
            {"title": "Neeli Meghamulalo", "sp": "0KI7IWhPBmzM4x059v5W6d"},
            {"title": 'Bangaari Bangaari (From "Mension House Mallesh")', "sp": "71wqxr5KGqH1PtSJY7Ot32"},
            {"title": "Modalainthile (Telugu Version)", "sp": "2FvDAZiQ9K53xFjFrsGx5e"},
            {"title": "Endharo Cheppinna", "sp": "7cpVOnJz4b0PAE3VhRKg6Q"},
            {"title": "Em Jaruguthondhi", "sp": "2bmUK5Th4OChl5q1H028qa"},
            {"title": "Maguva Maguva", "sp": "3rSyBBiLQZdifv5GFpsQmC"},
            {"title": "Oka Lailakosam", "sp": "0ijX4tdjjiiWXWIk5PxcEE"},
        ],
        "nostalgic": [
            {"title": "Samajavaragamana", "sp": "3j9DrRebdWK1jkpOw9FZUy"},
            {"title": "Buttabomma - Telugu", "sp": "0dnDTvdUco2UbaBjUtPxNS"},
            {"title": "Inkem Inkem Inkem Kaavaale", "sp": "3hglFJgXWPZUlHLfiDO35b"},
            {"title": "Vachinde", "sp": "2MeFfFMbaRDokOKwCJoxR8"},
            {"title": "MAYA CHESESAVE", "sp": "0aJocuPLwipMx6YmqjCiuw"},
            {"title": "Maguva Maguva", "sp": "3rSyBBiLQZdifv5GFpsQmC"},
            {"title": "Apudo Ipudo", "sp": "01uUuX3157r7G90Gb7LKQC"},
        ],
        "confident": [
            {"title": 'Eyy Bidda Idhi Naa Adda (From "Pushpa - The Rise")(Telugu)', "sp": "7e6J0HgooHYVi4SwdOB2OM"},
            {"title": 'Naatu Naatu (From "Rrr")', "sp": "4iKGu3xtvm90eBw0EIPWJP"},
            {"title": "Mind Block", "sp": "4q4PNCWRo90nUTILn6Y048"},
            {"title": 'Komuram Bheemudo (From "Rrr")', "sp": "7G8LfMpY6TGN9dbZ9m0Jdd"},
            {"title": "Saahore Baahubali", "sp": "0bRCRY10cmf7RuXMvblAks"},
            {"title": "Pakka Local", "sp": "5rPM9EITEGWpCJYIcedu6q"},
            {"title": "Kurchi Madathapetti", "sp": "4X09IuSKCHSrwtZuGoJD0r"},
        ],
        "bored": [
            {"title": 'Oo Antava Oo Oo Antava (From "Pushpa - The Rise")(Telugu)', "sp": "3szxldqiYs7nkvtmooRod8"},
            {"title": "Top Lesi Poddi", "sp": "4HTNf7HP0VCxrcxWtanJx7"},
            {"title": "Jigelu Rani", "sp": "0dw216k4UD9HVVNnXLMziC"},
            {"title": "Ammadu Let's Do Kummudu", "sp": "2qPJtWoPESkEDsmDntnVpE"},
            {"title": 'Ranjithame (From "Vaarasudu") [Telugu]', "sp": "0gZibDOwioMCck3d5nExjl"},
            {"title": "Kurchi Madathapetti", "sp": "4X09IuSKCHSrwtZuGoJD0r"},
        ],
    },
    "en": {
        "happy": [
            {"title": 'Happy - From "Despicable Me 2"', "sp": "60nZcImufyMA1MKQY3dcCH"},
            {"title": "Uptown Funk (feat. Bruno Mars)", "sp": "32OlwWuMpZ6b0aN2RZOeMS"},
            {"title": "Walking On Sunshine", "sp": "05wIrZSwuaVWhcv5FfqeH0"},
            {"title": "Shake It Off", "sp": "0cqRj7pUJDkTCEsJkx8snD"},
            {"title": "Don't Stop Me Now - Remastered 2011", "sp": "5T8EDUDqKcs6OSOwEsfqG7"},
            {"title": "Sunflower - Spider-Man: Into the Spider-Verse", "sp": "3KkXRkHbMCARz0aVfEt68P"},
            {"title": "good 4 u", "sp": "4ZtFanR9U6ndgddUvNcjcG"},
            {"title": "As It Was", "sp": "4LRPiXqCikLlN15c3yImP7"},
            {"title": "Anti-Hero", "sp": "0V3wPSX9ygBnCm8psDIegu"},
            {"title": "Dance Monkey", "sp": "2XU0oxnq2qxCpomAAuJY8K"},
            {"title": "Cheap Thrills", "sp": "27SdWb2rFzO6GWiYDBTD9j"},
            {"title": "Flowers", "sp": "05eGqWXAcALAiOeIObqKPj"},
            {"title": "Blinding Lights", "sp": "0VjIjW4GlUZAMYd2vXMi3b"},
            {"title": "Levitating (feat. DaBaby)", "sp": "463CkQjx2Zk1yXoBuierM9"},
            {"title": "Shallow", "sp": "2VxeLyX666F8uXCJ0dZF8B"},
        ],
        "sad": [
            {"title": "Someone Like You", "sp": "1zwMYTA5nlNjZxYrvBB2pV"},
            {"title": "Fix You", "sp": "7LVHVU3tWfcxj5aiPFEW4Q"},
            {"title": "Yesterday - Remastered 2009", "sp": "3BQHpFgAp4l80e1XslIjNI"},
            {"title": "drivers license", "sp": "5wANPM4fQCJwkGd4rN57mH"},
            {"title": "lovely (with Khalid)", "sp": "0u2P5u6lvoDfwTYjAADbn4"},
            {"title": "Memories", "sp": "4cktbXiXOapiLBMprHFErI"},
            {"title": "All of Me", "sp": "3U4isOIWM3VvDubwSI3y7a"},
            {"title": "Track 5hnobBMY", "sp": "5hnobBMYnYcnxuNMjbMJKx"},
            {"title": "The Night We Met", "sp": "3hRV0jL3vUpRrcy398teAU"},
        ],
        "romantic": [
            {"title": "Perfect", "sp": "0tgVpDi06FyKpA1z0VMD4v"},
            {"title": "All of Me", "sp": "3U4isOIWM3VvDubwSI3y7a"},
            {"title": "Thinking out Loud", "sp": "34gCuhDGsG4bRPIf9bb02f"},
            {"title": "Shallow", "sp": "2VxeLyX666F8uXCJ0dZF8B"},
            {"title": "Lover", "sp": "1dGr1c8CrMLDpV6mPbImSI"},
            {"title": "Algorithm", "sp": "7f0vVL3xi4i78Rv5Ptn2s1"},
            {"title": "Track 2LfBqnsC", "sp": "2LfBqnsCVoQgFAeJNnpitT"},
            {"title": "Track 44AyOl4q", "sp": "44AyOl4qWwall3m0o8IYEM"},
            {"title": "Track 6YHEMoNP", "sp": "6YHEMoNPbcheiWS3pGp4PB"},
            {"title": "Flowers", "sp": "05eGqWXAcALAiOeIObqKPj"},
        ],
        "energetic": [
            {"title": "Stronger", "sp": "4fzsfWzRhPawzqhX8Qt9F3"},
            {"title": "Titanium (feat. Sia)", "sp": "0TDLuuLlV54CkRRUOahJb4"},
            {"title": "Eye of the Tiger", "sp": "2KH16WveTQWT6KOG9Rg6e2"},
            {"title": "Lose Yourself", "sp": "5Z01UMMf7V1o0MzF86s6WJ"},
            {"title": "Thunder", "sp": "1zB4vmk8tFRmM9UULNzbLB"},
            {"title": "Track 69yfbpvm", "sp": "69yfbpvmkzOdQgqTBmWuik"},
            {"title": "Blinding Lights", "sp": "0VjIjW4GlUZAMYd2vXMi3b"},
            {"title": "HUMBLE.", "sp": "7KXjTSCq5nL1LoYtL7XAwS"},
        ],
        "stressed": [
            {"title": "Someone Like You", "sp": "1zwMYTA5nlNjZxYrvBB2pV"},
            {"title": "Fix You", "sp": "7LVHVU3tWfcxj5aiPFEW4Q"},
            {"title": "The Night We Met", "sp": "3hRV0jL3vUpRrcy398teAU"},
            {"title": "Track 5hnobBMY", "sp": "5hnobBMYnYcnxuNMjbMJKx"},
            {"title": "lovely (with Khalid)", "sp": "0u2P5u6lvoDfwTYjAADbn4"},
            {"title": "drivers license", "sp": "5wANPM4fQCJwkGd4rN57mH"},
            {"title": "What Makes You Beautiful", "sp": "4cluDES4hQEUhmXj6TXkSo"},
        ],
        "angry": [
            {"title": "Eye of the Tiger", "sp": "2KH16WveTQWT6KOG9Rg6e2"},
            {"title": "Lose Yourself", "sp": "5Z01UMMf7V1o0MzF86s6WJ"},
            {"title": "Stronger", "sp": "4fzsfWzRhPawzqhX8Qt9F3"},
            {"title": "Thunder", "sp": "1zB4vmk8tFRmM9UULNzbLB"},
            {"title": "Track 69yfbpvm", "sp": "69yfbpvmkzOdQgqTBmWuik"},
            {"title": "Killing In The Name", "sp": "59WN2psjkt1tyaxjspN8fp"},
            {"title": "In the End", "sp": "60a0Rd6pjrkxjPbaKzXjfq"},
        ],
        "chill": [
            {"title": "Viva La Vida", "sp": "1mea3bSkSGXuIRvnydlB5b"},
            {"title": "Mr. Blue Sky", "sp": "2RlgNHKcydI9sayD2Df2xp"},
            {"title": "Hotel California - 2013 Remaster", "sp": "40riOy7x9W7GXjyGp4pjAv"},
            {"title": "Shape of You", "sp": "7qiZfU4dY1lWllzX7mPBI3"},
            {"title": "Blinding Lights", "sp": "0VjIjW4GlUZAMYd2vXMi3b"},
            {"title": "golden hour", "sp": "4yNk9iz9WVJikRFle3XEvn"},
        ],
        "nostalgic": [
            {"title": "Bohemian Rhapsody", "sp": "3z8h0TU7ReDPLIbEnYhWZb"},
            {"title": "Hotel California - 2013 Remaster", "sp": "40riOy7x9W7GXjyGp4pjAv"},
            {"title": "Yesterday - Remastered 2009", "sp": "3BQHpFgAp4l80e1XslIjNI"},
            {"title": "Track 2lcHypYG", "sp": "2lcHypYGLyh6YEpP0fF5Xo"},
            {"title": "Viva La Vida", "sp": "1mea3bSkSGXuIRvnydlB5b"},
            {"title": "Africa", "sp": "2374M0fQpWi3dLnB54qaLX"},
            {"title": "Take on Me", "sp": "2WfaOiMkCvy7F5fcp2zZ8L"},
            {"title": "September", "sp": "2grjqo0Frpf2okIBiifQKs"},
            {"title": "Memories", "sp": "4cktbXiXOapiLBMprHFErI"},
        ],
        "confident": [
            {"title": "Stronger", "sp": "4fzsfWzRhPawzqhX8Qt9F3"},
            {"title": "Eye of the Tiger", "sp": "2KH16WveTQWT6KOG9Rg6e2"},
            {"title": "Lose Yourself", "sp": "5Z01UMMf7V1o0MzF86s6WJ"},
            {"title": "Blinding Lights", "sp": "0VjIjW4GlUZAMYd2vXMi3b"},
            {"title": "Shallow", "sp": "2VxeLyX666F8uXCJ0dZF8B"},
            {"title": "good 4 u", "sp": "4ZtFanR9U6ndgddUvNcjcG"},
            {"title": "Anti-Hero", "sp": "0V3wPSX9ygBnCm8psDIegu"},
            {"title": "HUMBLE.", "sp": "7KXjTSCq5nL1LoYtL7XAwS"},
            {"title": "Track 15FGLQL5", "sp": "15FGLQL5Ko4VxfVVWRz1A2"},
        ],
        "bored": [
            {"title": "Viva La Vida", "sp": "1mea3bSkSGXuIRvnydlB5b"},
            {"title": "Mr. Blue Sky", "sp": "2RlgNHKcydI9sayD2Df2xp"},
            {"title": "Shape of You", "sp": "7qiZfU4dY1lWllzX7mPBI3"},
            {"title": "Shake It Off", "sp": "0cqRj7pUJDkTCEsJkx8snD"},
            {"title": "Levitating (feat. DaBaby)", "sp": "463CkQjx2Zk1yXoBuierM9"},
            {"title": "Dance Monkey", "sp": "2XU0oxnq2qxCpomAAuJY8K"},
            {"title": "September", "sp": "2grjqo0Frpf2okIBiifQKs"},
            {"title": "Don't Stop Me Now - Remastered 2011", "sp": "5T8EDUDqKcs6OSOwEsfqG7"},
        ],
    },
}
