"""Curated Spotify track IDs by mood and language. Embed URL plays 30s preview."""

def _t(tid, name, artist):
    return {"id": tid, "name": name, "artist": artist,
            "embed_url": f"https://open.spotify.com/embed/track/{tid}?utm_source=generator&theme=0"}

TRACKS = {
  "happy": {
    "en": [
      _t("60nZcImufyMA1MKQY3dcCH","Happy","Pharrell Williams"),
      _t("32OlwWuMpZ6b0aN2RZOeMS","Uptown Funk","Bruno Mars"),
      _t("5T8EDUDqKcs6OSOwEsfqG7","Don't Stop Me Now","Queen"),
      _t("1WkMMavIMc4JZ8cfMmxHkI","Can't Stop the Feeling","Justin Timberlake"),
      _t("6KgBpzKbf3PflyByBlTrhQ","Good as Hell","Lizzo"),
      _t("0cqRj7pUJDkTCEsJkx8snD","Shake It Off","Taylor Swift"),
      _t("4hObp5bmIJ3PP3cKA9K9GY","Don't Worry Be Happy","Bobby McFerrin"),
      _t("3DXncPQOG4VBw3QHh3S817","Sugar","Maroon 5"),
    ],
    "hi": [
      _t("1GWLtn1hLkMv1MhYMIaQdS","Badtameez Dil","Benny Dayal"),
      _t("6cFZ4PLC68jez1kzmNNQXM","Balam Pichkari","Arijit Singh"),
      _t("1k2SQDeGjrFOjTi3nZMOWt","Kar Gayi Chull","Badshah"),
      _t("7JJmb5XwzOqEYRiLsDbMrc","London Thumakda","Labh Janjua"),
      _t("1NGMQR0zMiWEL2xmgpOO1T","Gallan Goodiyan","Shankar Mahadevan"),
      _t("5ftamIDoDScSn6JEYFvnOa","Dil Dhadakne Do","Priyanka Chopra"),
      _t("4YCPYyaJWtbRME7JzGMsZ6","Nachde Ne Saare","Jasleen Royal"),
      _t("3pIGm1bJqWGHfKS5gUbLFS","Kala Chashma","Amar Arshi"),
    ],
    "te": [
      _t("4pbJqGIASGPr0ZpGpnWkDn","Butta Bomma","Armaan Malik"),
      _t("6tV1bNLiIDIpF88hAiE0N2","Ramuloo Ramulaa","Anurag Kulkarni"),
      _t("5MwTHVjOyShNjJO9cE5Oce","Samajavaragamana","Sid Sriram"),
      _t("1wVGmCwaBPJIBxlSMf3Ems","Oo Antava","Indravathi Chauhan"),
      _t("6HUdDF5GxJLOgYlnEaBPHn","Srivalli","Javed Ali"),
      _t("2ygRRmdqqJgXJYbNgbPzsy","Naatu Naatu","Rahul Sipligunj"),
      _t("0TK2YIli9AstIKmHpoR09S","Buttabomma","Armaan Malik"),
      _t("4kbGwULPfZJiJiAQkMNpjE","Rangamma Mangamma","Mangli"),
    ],
  },
  "sad": {
    "en": [
      _t("1zwMYTA5nlNjZxYrvBB2pV","Someone Like You","Adele"),
      _t("7LVHVU3tWfcxj5aiPFEW4Q","Fix You","Coldplay"),
      _t("7qEHsqek33rTcFNT9PFqLf","Someone You Loved","Lewis Capaldi"),
      _t("5Nm9ERjJZ5oyfXZTECKmRt","Stay With Me","Sam Smith"),
      _t("1HNkqx9Ahdgi1Ixy2xkKkL","Photograph","Ed Sheeran"),
      _t("3JOVTQ5h8HGFnDdp4VT3MP","Hurt","Johnny Cash"),
      _t("4gphxUgq0JSFv2BCLhNDiE","Yesterday","The Beatles"),
      _t("43zdsphuZLzwA9k4DJhU0I","When The Party's Over","Billie Eilish"),
    ],
    "hi": [
      _t("3faMJEv0MxdVNgPqaGGc9I","Channa Mereya","Arijit Singh"),
      _t("4arF4fE1jTIFhKFvYwa6PG","Agar Tum Saath Ho","Arijit Singh"),
      _t("3GdPDaEArUJ7dlxuH6bXfe","Tujhe Kitna Chahne Lage","Arijit Singh"),
      _t("5oCnUmqEByzcWRunhCOOic","Phir Le Aaya Dil","Arijit Singh"),
      _t("1aDVJJuHVSZmRDshb8fFAO","Kabira","Tochi Raina"),
      _t("74X1epeRufHckHl0MUbYjD","Tum Hi Ho","Arijit Singh"),
      _t("7vBNxSPz5ZkTf2JgJEBIqc","Ae Dil Hai Mushkil","Arijit Singh"),
      _t("0SB7oZnhkfOFMHjVw2xO3F","Phir Le Aaya","Arijit Singh"),
    ],
    "te": [
      _t("2WpITVk3LI8RH6IvOFJYh5","Nee Kannu Neeli Samudram","Sid Sriram"),
      _t("7uGC6pMNMSE8GG4YRLBtP7","Inkem Inkem","Sid Sriram"),
      _t("6lDPvLMdGCVJcNxy9OdvPl","Yedetthu Mallele","Sid Sriram"),
      _t("3HjTcKLsIcMoGEX31gfhF2","Nenu Sailaja","Haricharan"),
      _t("0UwMd7J2VuMjWOFNpNJHcz","Ye Maaya Chesave","Chinmayi"),
      _t("5kGJt5w3JxKjnQxKiG9fRW","Nijamena","Haricharan"),
      _t("1i0bEhMcRaBT8KFA1GRnvF","Vachinde","Sid Sriram"),
      _t("7kMYnCdMkvpPgXYhS3p2YR","Kanulu Navainaa","Sid Sriram"),
    ],
  },
  "stressed": {
    "en": [
      _t("5fSQRaYEMFZLULNjBeNqv6","River Flows in You","Yiruma"),
      _t("7MXlTqOG07DxOHgoRseOhU","Only Time","Enya"),
      _t("6kkwzB6hXLIOlFnUogXbgN","Weightless","Marconi Union"),
      _t("5fvYpFIMnRuBOiGDSalTsL","Clair de Lune","Debussy"),
      _t("3RiPr603aXAo4GyrAYYpmN","Gymnopédie No.1","Erik Satie"),
      _t("5fGp7oIM6pwBOwkNF5vAhE","Sunset Lover","Petit Biscuit"),
      _t("7qiJBkRTsGjfCbGgj0YXYF","Breathe Me","Sia"),
      _t("3U4isOIWM3VvDubwSI3y7a","All of Me","John Legend"),
    ],
    "hi": [
      _t("2gUqVpDXCDW8vVBanlnfBr","Kun Faya Kun","A.R. Rahman"),
      _t("5nCi3TlEH9WyWxGF66VVlN","Tere Bina","A.R. Rahman"),
      _t("0Io4sDNcDUhKr5IXdEuNrG","Iktara","Kavita Seth"),
      _t("6kIdHKbnPnwKJuqnRToJWr","Jashn-E-Bahaara","Javed Ali"),
      _t("26LjNf0iWQfvBmqKNxpPyH","Ilahi","Arijit Singh"),
      _t("4WbUdm1zCGWbFBMYtXwXcQ","Tum Se Hi","Mohit Chauhan"),
      _t("2I6XAIGbONwpIcz2SFTdyK","Tera Ban Jaunga","Akhil Sachdeva"),
      _t("5wR0r2MYmx2JJqLDUjAKbn","Shaam","Arijit Singh"),
    ],
    "te": [
      _t("5MwTHVjOyShNjJO9cE5Oce","Samajavaragamana","Sid Sriram"),
      _t("7uGC6pMNMSE8GG4YRLBtP7","Inkem Inkem","Sid Sriram"),
      _t("1i0bEhMcRaBT8KFA1GRnvF","Vachinde","Sid Sriram"),
      _t("2ygRRmdqqJgXJYbNgbPzsy","Naatu Naatu","Rahul Sipligunj"),
      _t("6lDPvLMdGCVJcNxy9OdvPl","Yedetthu Mallele","Sid Sriram"),
      _t("5kGJt5w3JxKjnQxKiG9fRW","Nijamena","Haricharan"),
    ],
  },
  "angry": {
    "en": [
      _t("7w87IxuO7BDcJ3YUqCyMTT","Lose Yourself","Eminem"),
      _t("2KH16WveTQWT6KOG9Rg6e2","Eye of the Tiger","Survivor"),
      _t("0pqnGHJpmpxLKifKRmU0WP","Believer","Imagine Dragons"),
      _t("2DlHlPMa4M17kufBvI2lEN","Numb","Linkin Park"),
      _t("5W3cjX2J3tjhG8zb6u0qHn","Thunderstruck","AC/DC"),
      _t("7lQ8MOhq6IN2w8EYcFNSUk","In the End","Linkin Park"),
      _t("1v1oIWf2Xgh54kIWuKMXfp","Rap God","Eminem"),
    ],
    "hi": [
      _t("5n5M2KBjHt8OqrAlkBtLmb","Malhari","Vishal Dadlani"),
      _t("0gD02SRqbSNkZLPGVqVJbp","Khalibali","Shivam Pathak"),
      _t("3pIGm1bJqWGHfKS5gUbLFS","Kala Chashma","Amar Arshi"),
      _t("1k2SQDeGjrFOjTi3nZMOWt","Kar Gayi Chull","Badshah"),
      _t("41sEPwNiLMPGDxh7vl3bXb","Zingaat","Ajay-Atul"),
      _t("2i0e4BVHaHGbSz7OPHDulj","Apna Time Aayega","Ranveer Singh"),
    ],
    "te": [
      _t("2ygRRmdqqJgXJYbNgbPzsy","Naatu Naatu","Rahul Sipligunj"),
      _t("4kbGwULPfZJiJiAQkMNpjE","Rangamma Mangamma","Mangli"),
      _t("1wVGmCwaBPJIBxlSMf3Ems","Oo Antava","Indravathi Chauhan"),
      _t("6tV1bNLiIDIpF88hAiE0N2","Ramuloo Ramulaa","Anurag Kulkarni"),
      _t("4pbJqGIASGPr0ZpGpnWkDn","Butta Bomma","Armaan Malik"),
      _t("6HUdDF5GxJLOgYlnEaBPHn","Srivalli","Javed Ali"),
    ],
  },
  "romantic": {
    "en": [
      _t("0tgVpDi06FyKpA1z0VMD4v","Perfect","Ed Sheeran"),
      _t("3U4isOIWM3VvDubwSI3y7a","All of Me","John Legend"),
      _t("44AyOl4qVkzS48vBsbNXaC","Can't Help Falling in Love","Elvis Presley"),
      _t("3d9DChrdc6BOeFsbrZ3Is0","Something Just Like This","Coldplay"),
      _t("7BKLCZ1jbUBVqRi2FVlTVw","Closer","The Chainsmokers"),
      _t("2nLtzopw4rPReszdYBJU6h","Thinking Out Loud","Ed Sheeran"),
      _t("1BxfuPKGuaTgP7aM0Bbdwr","Unchained Melody","Righteous Brothers"),
    ],
    "hi": [
      _t("74X1epeRufHckHl0MUbYjD","Tum Hi Ho","Arijit Singh"),
      _t("0dBW6ZsW8skfvoRfcUaC3t","Kal Ho Naa Ho","Sonu Nigam"),
      _t("2I6XAIGbONwpIcz2SFTdyK","Tera Ban Jaunga","Akhil Sachdeva"),
      _t("3faMJEv0MxdVNgPqaGGc9I","Channa Mereya","Arijit Singh"),
      _t("3GdPDaEArUJ7dlxuH6bXfe","Tujhe Kitna Chahne Lage","Arijit Singh"),
      _t("26LjNf0iWQfvBmqKNxpPyH","Ilahi","Arijit Singh"),
      _t("4WbUdm1zCGWbFBMYtXwXcQ","Tum Se Hi","Mohit Chauhan"),
    ],
    "te": [
      _t("5MwTHVjOyShNjJO9cE5Oce","Samajavaragamana","Sid Sriram"),
      _t("7uGC6pMNMSE8GG4YRLBtP7","Inkem Inkem","Sid Sriram"),
      _t("1i0bEhMcRaBT8KFA1GRnvF","Vachinde","Sid Sriram"),
      _t("2WpITVk3LI8RH6IvOFJYh5","Nee Kannu Neeli Samudram","Sid Sriram"),
      _t("5kGJt5w3JxKjnQxKiG9fRW","Nijamena","Haricharan"),
      _t("7kMYnCdMkvpPgXYhS3p2YR","Kanulu Navainaa","Sid Sriram"),
    ],
  },
  "energetic": {
    "en": [
      _t("0DiDStADDVh3SvAsoJAFMk","Levels","Avicii"),
      _t("0lHAMNU8RGiIObDJcEYJlr","Titanium","David Guetta"),
      _t("7GhIk7Il098yCjg4BQjzvb","Lean On","Major Lazer"),
      _t("2cGxRwrMyEAp8dEbuZaVv6","Break Free","Ariana Grande"),
      _t("3a1lNhkSLSkpJE4MSHpDu9","Faded","Alan Walker"),
      _t("6habFhsLcdGF3adndFjJ0z","Wake Me Up","Avicii"),
      _t("2DlHlPMa4M17kufBvI2lEN","Numb","Linkin Park"),
    ],
    "hi": [
      _t("5n5M2KBjHt8OqrAlkBtLmb","Malhari","Vishal Dadlani"),
      _t("41sEPwNiLMPGDxh7vl3bXb","Zingaat","Ajay-Atul"),
      _t("3pIGm1bJqWGHfKS5gUbLFS","Kala Chashma","Amar Arshi"),
      _t("1k2SQDeGjrFOjTi3nZMOWt","Kar Gayi Chull","Badshah"),
      _t("0gD02SRqbSNkZLPGVqVJbp","Khalibali","Shivam Pathak"),
      _t("1GWLtn1hLkMv1MhYMIaQdS","Badtameez Dil","Benny Dayal"),
    ],
    "te": [
      _t("2ygRRmdqqJgXJYbNgbPzsy","Naatu Naatu","Rahul Sipligunj"),
      _t("4kbGwULPfZJiJiAQkMNpjE","Rangamma Mangamma","Mangli"),
      _t("1wVGmCwaBPJIBxlSMf3Ems","Oo Antava","Indravathi Chauhan"),
      _t("6tV1bNLiIDIpF88hAiE0N2","Ramuloo Ramulaa","Anurag Kulkarni"),
      _t("6HUdDF5GxJLOgYlnEaBPHn","Srivalli","Javed Ali"),
      _t("4pbJqGIASGPr0ZpGpnWkDn","Butta Bomma","Armaan Malik"),
    ],
  },
  "chill": {
    "en": [
      _t("5fGp7oIM6pwBOwkNF5vAhE","Sunset Lover","Petit Biscuit"),
      _t("3FtYbEfBqAlGO46NUDQSAt","Electric Feel","MGMT"),
      _t("2X485T9Z5Ly0xyaghN73ed","Let It Happen","Tame Impala"),
      _t("6kkwzB6hXLIOlFnUogXbgN","Weightless","Marconi Union"),
      _t("7qiJBkRTsGjfCbGgj0YXYF","Breathe Me","Sia"),
      _t("5fSQRaYEMFZLULNjBeNqv6","River Flows in You","Yiruma"),
    ],
    "hi": [
      _t("0Io4sDNcDUhKr5IXdEuNrG","Iktara","Kavita Seth"),
      _t("26LjNf0iWQfvBmqKNxpPyH","Ilahi","Arijit Singh"),
      _t("5nCi3TlEH9WyWxGF66VVlN","Tere Bina","A.R. Rahman"),
      _t("2gUqVpDXCDW8vVBanlnfBr","Kun Faya Kun","A.R. Rahman"),
      _t("4WbUdm1zCGWbFBMYtXwXcQ","Tum Se Hi","Mohit Chauhan"),
    ],
    "te": [
      _t("5MwTHVjOyShNjJO9cE5Oce","Samajavaragamana","Sid Sriram"),
      _t("7uGC6pMNMSE8GG4YRLBtP7","Inkem Inkem","Sid Sriram"),
      _t("1i0bEhMcRaBT8KFA1GRnvF","Vachinde","Sid Sriram"),
      _t("5kGJt5w3JxKjnQxKiG9fRW","Nijamena","Haricharan"),
      _t("6lDPvLMdGCVJcNxy9OdvPl","Yedetthu Mallele","Sid Sriram"),
    ],
  },
  "nostalgic": {
    "en": [
      _t("4u7EnebtmKWzUH433cf5Qv","Bohemian Rhapsody","Queen"),
      _t("40riOy7x9W7GXjyGp4pjAv","Hotel California","Eagles"),
      _t("7o2CTH4ctstm8TNelqjb51","Sweet Child O' Mine","Guns N' Roses"),
      _t("3BQHpFgAp4l80e1XslIjNI","Piano Man","Billy Joel"),
      _t("4gphxUgq0JSFv2BCLhNDiE","Yesterday","The Beatles"),
      _t("1mea3bSkSGXuIRvnydlB5b","Viva La Vida","Coldplay"),
    ],
    "hi": [
      _t("0dBW6ZsW8skfvoRfcUaC3t","Kal Ho Naa Ho","Sonu Nigam"),
      _t("2gUqVpDXCDW8vVBanlnfBr","Kun Faya Kun","A.R. Rahman"),
      _t("6kIdHKbnPnwKJuqnRToJWr","Jashn-E-Bahaara","Javed Ali"),
      _t("1aDVJJuHVSZmRDshb8fFAO","Kabira","Tochi Raina"),
      _t("4arF4fE1jTIFhKFvYwa6PG","Agar Tum Saath Ho","Arijit Singh"),
    ],
    "te": [
      _t("5MwTHVjOyShNjJO9cE5Oce","Samajavaragamana","Sid Sriram"),
      _t("7uGC6pMNMSE8GG4YRLBtP7","Inkem Inkem","Sid Sriram"),
      _t("3HjTcKLsIcMoGEX31gfhF2","Nenu Sailaja","Haricharan"),
      _t("0UwMd7J2VuMjWOFNpNJHcz","Ye Maaya Chesave","Chinmayi"),
    ],
  },
  "confident": {
    "en": [
      _t("7ccI9cSH0CMnpwGJyQMqRO","We Are the Champions","Queen"),
      _t("1v1oIWf2Xgh54kIWuKMXfp","Rap God","Eminem"),
      _t("7w87IxuO7BDcJ3YUqCyMTT","Lose Yourself","Eminem"),
      _t("0pqnGHJpmpxLKifKRmU0WP","Believer","Imagine Dragons"),
      _t("2KH16WveTQWT6KOG9Rg6e2","Eye of the Tiger","Survivor"),
      _t("5T8EDUDqKcs6OSOwEsfqG7","Don't Stop Me Now","Queen"),
    ],
    "hi": [
      _t("2i0e4BVHaHGbSz7OPHDulj","Apna Time Aayega","Ranveer Singh"),
      _t("5n5M2KBjHt8OqrAlkBtLmb","Malhari","Vishal Dadlani"),
      _t("0gD02SRqbSNkZLPGVqVJbp","Khalibali","Shivam Pathak"),
      _t("1GWLtn1hLkMv1MhYMIaQdS","Badtameez Dil","Benny Dayal"),
      _t("3pIGm1bJqWGHfKS5gUbLFS","Kala Chashma","Amar Arshi"),
    ],
    "te": [
      _t("2ygRRmdqqJgXJYbNgbPzsy","Naatu Naatu","Rahul Sipligunj"),
      _t("6tV1bNLiIDIpF88hAiE0N2","Ramuloo Ramulaa","Anurag Kulkarni"),
      _t("1wVGmCwaBPJIBxlSMf3Ems","Oo Antava","Indravathi Chauhan"),
      _t("6HUdDF5GxJLOgYlnEaBPHn","Srivalli","Javed Ali"),
      _t("4pbJqGIASGPr0ZpGpnWkDn","Butta Bomma","Armaan Malik"),
    ],
  },
  "bored": {
    "en": [
      _t("1mea3bSkSGXuIRvnydlB5b","Viva La Vida","Coldplay"),
      _t("2RlgNHKcydI9sayD2Df2xp","Mr. Blue Sky","ELO"),
      _t("32OlwWuMpZ6b0aN2RZOeMS","Uptown Funk","Bruno Mars"),
      _t("60nZcImufyMA1MKQY3dcCH","Happy","Pharrell Williams"),
      _t("3a1lNhkSLSkpJE4MSHpDu9","Faded","Alan Walker"),
      _t("7GhIk7Il098yCjg4BQjzvb","Lean On","Major Lazer"),
    ],
    "hi": [
      _t("1k2SQDeGjrFOjTi3nZMOWt","Kar Gayi Chull","Badshah"),
      _t("41sEPwNiLMPGDxh7vl3bXb","Zingaat","Ajay-Atul"),
      _t("6cFZ4PLC68jez1kzmNNQXM","Balam Pichkari","Arijit Singh"),
      _t("7JJmb5XwzOqEYRiLsDbMrc","London Thumakda","Labh Janjua"),
      _t("1GWLtn1hLkMv1MhYMIaQdS","Badtameez Dil","Benny Dayal"),
    ],
    "te": [
      _t("4pbJqGIASGPr0ZpGpnWkDn","Butta Bomma","Armaan Malik"),
      _t("2ygRRmdqqJgXJYbNgbPzsy","Naatu Naatu","Rahul Sipligunj"),
      _t("6tV1bNLiIDIpF88hAiE0N2","Ramuloo Ramulaa","Anurag Kulkarni"),
      _t("6HUdDF5GxJLOgYlnEaBPHn","Srivalli","Javed Ali"),
      _t("1wVGmCwaBPJIBxlSMf3Ems","Oo Antava","Indravathi Chauhan"),
    ],
  },
}
